# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('0', '作息'), ('1', '跑步'), ('2', '阅读')], max_length=16)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('PEND', '作息'), ('ACTIVE', '进行中'), ('PAUSED', '停止'), ('COMPLETE', '完成')], max_length=32)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_participants', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField(default=0)),
                ('bonus_all', models.FloatField(default=0)),
                ('logoimgurl', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='RunningGoal',
            fields=[
                ('goal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('activity_type', models.CharField(default='作息', max_length=32)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_day', models.IntegerField(default=0)),
                ('left_day', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PEND', '作息'), ('ACTIVE', '进行中'), ('PAUSED', '停止'), ('COMPLETE', '完成')], default='ACTIVE', max_length=32)),
                ('mode', models.CharField(choices=[('S', '学生'), ('T', '尝试'), ('N', '普通')], default='N', max_length=10)),
                ('guaranty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('running_type', models.IntegerField(default=0)),
                ('goal_distance', models.FloatField()),
                ('kilos_day', models.FloatField(null=True)),
                ('mul', models.FloatField(default=1)),
                ('fin_all', models.FloatField()),
                ('bonus_all', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunningPunchRecord',
            fields=[
                ('punch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField()),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('voucher', models.ImageField(blank=True, upload_to='')),
                ('distance', models.FloatField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch', to='on.RunningGoal')),
            ],
        ),
        migrations.CreateModel(
            name='SleepingGoal',
            fields=[
                ('goal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('activity_type', models.CharField(default='作息', max_length=32)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_day', models.IntegerField(default=0)),
                ('left_day', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PEND', '作息'), ('ACTIVE', '进行中'), ('PAUSED', '停止'), ('COMPLETE', '完成')], default='ACTIVE', max_length=32)),
                ('mode', models.CharField(choices=[('S', '学生'), ('T', '尝试'), ('N', '普通')], default='N', max_length=10)),
                ('guaranty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('getup_time', models.DateTimeField()),
                ('goal_distance', models.FloatField()),
                ('kilos_day', models.FloatField(null=True)),
                ('mul', models.FloatField(default=1)),
                ('fin_all', models.FloatField()),
                ('bonus_all', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SleepingPunchRecord',
            fields=[
                ('punch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField()),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('before_sleep_time', models.DateTimeField()),
                ('user_get_up_time', models.DateTimeField(null=True)),
                ('check_time', models.DateTimeField(null=True)),
                ('user_check_time', models.DateTimeField(null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch', to='on.SleepingGoal')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sex', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('wechat_id', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('headimgurl', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_times', models.IntegerField(default=0)),
                ('join_times', models.IntegerField(default=0)),
                ('finish_days', models.IntegerField(default=0)),
                ('all_coefficient', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='on.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('relation_id', models.UUIDField(default=uuid.UUID('aea14feb-d646-419a-a21f-8cc2c0c4ba7b'), editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('friend_id', models.UUIDField()),
                ('group_id', models.IntegerField(null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('D', '延时'), ('NS', '免签')], max_length=32)),
                ('number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='on.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_info', models.CharField(max_length=255)),
                ('user_wechat_id', models.CharField(max_length=255)),
                ('goal_id', models.IntegerField()),
                ('trade_type', models.CharField(max_length=255)),
                ('trade_state', models.IntegerField(default=0)),
                ('trade_state_desc', models.CharField(max_length=255)),
                ('bank_type', models.CharField(max_length=255, null=True)),
                ('total_fee', models.IntegerField()),
                ('actual_fee', models.IntegerField()),
                ('fee_type', models.CharField(max_length=255, null=True)),
                ('wechat_transaction_id', models.CharField(max_length=255)),
                ('out_trade_id', models.CharField(max_length=255)),
                ('finish_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sleepinggoal',
            unique_together=set([('user_id', 'activity_type', 'status', 'start_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='runninggoal',
            unique_together=set([('user_id', 'activity_type', 'status', 'start_time')]),
        ),
        migrations.AddField(
            model_name='parise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on.UserInfo'),
        ),
    ]
